// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"time"

	uuid "github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

type Session struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	RefreshTokenHash string
	UserAgent        string
	ExpiresAt        time.Time
	CreatedAt        time.Time
	RefreshedAt      time.Time
	RevokedAt        null.Time
}

type User struct {
	ID          uuid.UUID
	OpenID      string
	IDP         string
	Email       string
	DisplayName null.String
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   null.Time
}
