// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.getSessionStmt, err = db.PrepareContext(ctx, getSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetSession: %w", err)
	}
	if q.getSessionByRefreshTokenHashStmt, err = db.PrepareContext(ctx, getSessionByRefreshTokenHash); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionByRefreshTokenHash: %w", err)
	}
	if q.getUserStmt, err = db.PrepareContext(ctx, getUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetUser: %w", err)
	}
	if q.listSessionsStmt, err = db.PrepareContext(ctx, listSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessions: %w", err)
	}
	if q.refreshSessionStmt, err = db.PrepareContext(ctx, refreshSession); err != nil {
		return nil, fmt.Errorf("error preparing query RefreshSession: %w", err)
	}
	if q.revokeSessionStmt, err = db.PrepareContext(ctx, revokeSession); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeSession: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.getSessionStmt != nil {
		if cerr := q.getSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionStmt: %w", cerr)
		}
	}
	if q.getSessionByRefreshTokenHashStmt != nil {
		if cerr := q.getSessionByRefreshTokenHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByRefreshTokenHashStmt: %w", cerr)
		}
	}
	if q.getUserStmt != nil {
		if cerr := q.getUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserStmt: %w", cerr)
		}
	}
	if q.listSessionsStmt != nil {
		if cerr := q.listSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsStmt: %w", cerr)
		}
	}
	if q.refreshSessionStmt != nil {
		if cerr := q.refreshSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing refreshSessionStmt: %w", cerr)
		}
	}
	if q.revokeSessionStmt != nil {
		if cerr := q.revokeSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeSessionStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                               DBTX
	tx                               *sql.Tx
	createSessionStmt                *sql.Stmt
	createUserStmt                   *sql.Stmt
	getSessionStmt                   *sql.Stmt
	getSessionByRefreshTokenHashStmt *sql.Stmt
	getUserStmt                      *sql.Stmt
	listSessionsStmt                 *sql.Stmt
	refreshSessionStmt               *sql.Stmt
	revokeSessionStmt                *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                               tx,
		tx:                               tx,
		createSessionStmt:                q.createSessionStmt,
		createUserStmt:                   q.createUserStmt,
		getSessionStmt:                   q.getSessionStmt,
		getSessionByRefreshTokenHashStmt: q.getSessionByRefreshTokenHashStmt,
		getUserStmt:                      q.getUserStmt,
		listSessionsStmt:                 q.listSessionsStmt,
		refreshSessionStmt:               q.refreshSessionStmt,
		revokeSessionStmt:                q.revokeSessionStmt,
	}
}
