// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlite

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  id,
  user_id,
  refresh_token_hash,
  user_agent,
  expires_at,
  created_at,
  refreshed_at
)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
  strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
)
RETURNING id, user_id, refresh_token_hash, user_agent, expires_at, created_at, refreshed_at, revoked_at
`

type CreateSessionParams struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	RefreshTokenHash string
	UserAgent        string
	ExpiresAt        time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.createSessionStmt, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RefreshedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, refresh_token_hash, user_agent, expires_at, created_at, refreshed_at, revoked_at FROM sessions
WHERE id = ? AND revoked_at IS NULL
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.queryRow(ctx, q.getSessionStmt, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RefreshedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByRefreshTokenHash = `-- name: GetSessionByRefreshTokenHash :one
SELECT id, user_id, refresh_token_hash, user_agent, expires_at, created_at, refreshed_at, revoked_at FROM sessions
WHERE refresh_token_hash = ? AND revoked_at IS NULL
`

func (q *Queries) GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.queryRow(ctx, q.getSessionByRefreshTokenHashStmt, getSessionByRefreshTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RefreshedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, user_id, refresh_token_hash, user_agent, expires_at, created_at, refreshed_at, revoked_at FROM sessions
WHERE user_id = ? AND revoked_at IS NULL
`

func (q *Queries) ListSessions(ctx context.Context, userID uuid.UUID) ([]Session, error) {
	rows, err := q.query(ctx, q.listSessionsStmt, listSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshTokenHash,
			&i.UserAgent,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RefreshedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshSession = `-- name: RefreshSession :one
UPDATE sessions
SET
  refresh_token_hash = ?1,
  user_agent = ?2,
  expires_at = ?3,
  refreshed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?4 AND revoked_at IS NULL
RETURNING id, user_id, refresh_token_hash, user_agent, expires_at, created_at, refreshed_at, revoked_at
`

type RefreshSessionParams struct {
	RefreshTokenHash string
	UserAgent        string
	ExpiresAt        time.Time
	ID               uuid.UUID
}

func (q *Queries) RefreshSession(ctx context.Context, arg RefreshSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.refreshSessionStmt, refreshSession,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.ExpiresAt,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RefreshedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET
  revoked_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.revokeSessionStmt, revokeSession, id)
	return err
}
