#:schema https://json.schemastore.org/any.json

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"
env_files = [".env"]

[build]
  args_bin = []
  bin = "./tmp/goweb"
  cmd = "go build -tags dev -buildvcs=false -o ./tmp/goweb ./cmd/goweb"
  delay = 1000
  entrypoint = ["./tmp/goweb", "serve", "-c", "goweb.dev.toml"]
  exclude_dir = ["bin", "tmp", "testdata", "frontend/node_modules", "frontend/src"]
  exclude_file = []
  exclude_regex = ["_test.go", "\\.db$", "\\.db-shm$", "\\.db-wal$"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "css", "js", "webmanifest"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
