// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health.sql

package db

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 'pong' AS message
`

func (q *Queries) Ping(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, ping)
	var message string
	err := row.Scan(&message)
	return message, err
}
