// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	uuid "github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

type Session struct {
	SessionID        uuid.UUID `db:"session_id" json:"sessionId"`
	UserID           uuid.UUID `db:"user_id" json:"userId"`
	RefreshTokenHash string    `db:"refresh_token_hash" json:"refreshTokenHash"`
	UserAgent        string    `db:"user_agent" json:"userAgent"`
	CreatedAt        time.Time `db:"created_at" json:"createdAt"`
	LastUsedAt       time.Time `db:"last_used_at" json:"lastUsedAt"`
	RevokedAt        null.Time `db:"revoked_at" json:"revokedAt"`
}

type User struct {
	UserID      uuid.UUID   `db:"user_id" json:"userId"`
	OpenID      string      `db:"open_id" json:"openId"`
	Provider    string      `db:"provider" json:"provider"`
	Email       string      `db:"email" json:"email"`
	DisplayName null.String `db:"display_name" json:"displayName"`
	CreatedAt   time.Time   `db:"created_at" json:"createdAt"`
	UpdatedAt   null.Time   `db:"updated_at" json:"updatedAt"`
	DeletedAt   null.Time   `db:"deleted_at" json:"deletedAt"`
}
