// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_token_hash, user_agent)
VALUES ($1, $2, $3)
RETURNING session_id, user_id, refresh_token_hash, user_agent, created_at, last_used_at, revoked_at
`

type CreateSessionParams struct {
	UserID           uuid.UUID `db:"user_id" json:"userId"`
	RefreshTokenHash string    `db:"refresh_token_hash" json:"refreshTokenHash"`
	UserAgent        string    `db:"user_agent" json:"userAgent"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.RefreshTokenHash, arg.UserAgent)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :one
UPDATE sessions
SET revoked_at = CURRENT_TIMESTAMP
WHERE refresh_token_hash = $1 AND revoked_at IS NULL
RETURNING session_id, user_id, refresh_token_hash, user_agent, created_at, last_used_at, revoked_at
`

func (q *Queries) RevokeSession(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, revokeSession, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const rotateSession = `-- name: RotateSession :one
UPDATE sessions
SET refresh_token_hash = $1, last_used_at = CURRENT_TIMESTAMP
WHERE refresh_token_hash = $2
  AND revoked_at IS NULL
  AND EXISTS (SELECT 1 FROM users WHERE users.user_id = sessions.user_id AND users.deleted_at IS NULL)
RETURNING session_id, user_id, refresh_token_hash, user_agent, created_at, last_used_at, revoked_at
`

type RotateSessionParams struct {
	NewRefreshTokenHash string `db:"new_refresh_token_hash" json:"newRefreshTokenHash"`
	RefreshTokenHash    string `db:"refresh_token_hash" json:"refreshTokenHash"`
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, rotateSession, arg.NewRefreshTokenHash, arg.RefreshTokenHash)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}
