// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (open_id, provider, email, display_name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (open_id, provider) DO
UPDATE SET email = EXCLUDED.email, display_name = EXCLUDED.display_name
WHERE users.deleted_at IS NULL
RETURNING user_id, open_id, provider, email, display_name, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	OpenID      string      `db:"open_id" json:"openId"`
	Provider    string      `db:"provider" json:"provider"`
	Email       string      `db:"email" json:"email"`
	DisplayName null.String `db:"display_name" json:"displayName"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.OpenID,
		arg.Provider,
		arg.Email,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.OpenID,
		&i.Provider,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, open_id, provider, email, display_name, created_at, updated_at, deleted_at FROM users
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.OpenID,
		&i.Provider,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, open_id, provider, email, display_name, created_at, updated_at, deleted_at FROM users
WHERE deleted_at IS NULL
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.OpenID,
			&i.Provider,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
