// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresql

import (
	"time"

	uuid "github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

type Session struct {
	ID               uuid.UUID `db:"id"`
	UserID           uuid.UUID `db:"user_id"`
	RefreshTokenHash string    `db:"refresh_token_hash"`
	UserAgent        string    `db:"user_agent"`
	RefreshedAt      time.Time `db:"refreshed_at"`
	CreatedAt        time.Time `db:"created_at"`
	ExpiresAt        time.Time `db:"expires_at"`
	RevokedAt        null.Time `db:"revoked_at"`
}

type User struct {
	ID          uuid.UUID   `db:"id"`
	OpenID      string      `db:"open_id"`
	IDP         string      `db:"idp"`
	Email       string      `db:"email"`
	DisplayName null.String `db:"display_name"`
	CreatedAt   time.Time   `db:"created_at"`
	UpdatedAt   time.Time   `db:"updated_at"`
	DeletedAt   null.Time   `db:"deleted_at"`
}
