// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package postgresql

import (
	"context"

	uuid "github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  open_id,
  idp,
  email,
  display_name,
  created_at,
  updated_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT (open_id, idp) DO
UPDATE SET
  email = EXCLUDED.email,
  display_name = EXCLUDED.display_name,
  updated_at = CURRENT_TIMESTAMP,
  deleted_at = NULL
RETURNING id, open_id, idp, email, display_name, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	OpenID      string      `db:"open_id"`
	IDP         string      `db:"idp"`
	Email       string      `db:"email"`
	DisplayName null.String `db:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.OpenID,
		arg.IDP,
		arg.Email,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OpenID,
		&i.IDP,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, open_id, idp, email, display_name, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OpenID,
		&i.IDP,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
